version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - ~/.config/claude:/home/node/.config/claude:cached
    command: sleep infinity
    ports:
      - 3000:3000

volumes:
  node_modules:
